export interface CatalogSpec {
  label: string;
  value: string;
}

const specs: Record<string, CatalogSpec[]> = {
  // --- PASAJEROS ---
  "Aventura Pro a Gasolina": [
    { label: "Motor", value: "2.0L Turbo Euro V" },
    { label: "Potencia", value: "231 HP" },
    { label: "Transmisión", value: "Manual / Automática" },
    { label: "Tracción", value: "4×4" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Verde · Negro · Gris · Blanco" },
  ],
  "Aventura a Gasolina": [
    { label: "Motor", value: "2.0L Turbo Euro II" },
    { label: "Potencia", value: "231 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Tracción", value: "4×4" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Gris · Rojo" },
  ],
  "Arena Sport Manual": [
    { label: "Motor", value: "1.5L WT Euro V" },
    { label: "Potencia", value: "112 HP" },
    { label: "Transmisión", value: "Manual 6 velocidades" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Rojo · Gris" },
  ],
  "Arena Sport Automático": [
    { label: "Motor", value: "1.5L WT Euro V" },
    { label: "Potencia", value: "112 HP" },
    { label: "Transmisión", value: "Automática CVT" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Rojo · Gris" },
  ],
  "Arena Pro": [
    { label: "Motor", value: "1.5L WT Euro V" },
    { label: "Potencia", value: "112 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Tracción", value: "4×4" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Gris" },
  ],
  "Nevado Manual": [
    { label: "Motor", value: "1.6L DVVT Euro V" },
    { label: "Potencia", value: "118 HP" },
    { label: "Transmisión", value: "Manual 5 velocidades" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Negro · Blanco · Rojo · Azul · Gris" },
  ],
  "Nevado Automático": [
    { label: "Motor", value: "1.5L Turbo Euro V" },
    { label: "Potencia", value: "147 HP" },
    { label: "Transmisión", value: "Automática" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Negro · Blanco · Gris" },
  ],
  "Tepuy Pro": [
    { label: "Motor", value: "1.5L Turbo Euro V" },
    { label: "Potencia", value: "181 HP" },
    { label: "Transmisión", value: "Automática" },
    { label: "Tracción", value: "4×4" },
    { label: "Pasajeros", value: "7" },
    { label: "Colores", value: "Blanco · Negro · Gris" },
  ],
  "Refine": [
    { label: "Motor", value: "2.0L DWT Turbo Euro VI" },
    { label: "Potencia", value: "Consultar" },
    { label: "Transmisión", value: "Automática" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Gris · Marrón" },
  ],
  "La Venezolana a Gasolina 4×2": [
    { label: "Motor", value: "2.0L WT Euro V" },
    { label: "Potencia", value: "145 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Gris · Rojo · Azul" },
  ],
  "La Venezolana a Diésel 4×2 y 4×4": [
    { label: "Motor", value: "2.8L Turbo Euro II" },
    { label: "Potencia", value: "137 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Tracción", value: "4×2 / 4×4" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Gris" },
  ],
  "La Venezolana Pro 4×4": [
    { label: "Motor", value: "2.0L Turbo Euro V" },
    { label: "Potencia", value: "188 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Tracción", value: "4×4" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Gris · Rojo" },
  ],
  "Savanna": [
    { label: "Motor", value: "1.5L Turbo Euro V" },
    { label: "Potencia", value: "150 HP" },
    { label: "Transmisión", value: "Automática" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "7" },
    { label: "Colores", value: "Blanco · Negro · Gris · Rojo" },
  ],
  "Élite": [
    { label: "Motor", value: "2.0L Turbo Euro V" },
    { label: "Potencia", value: "231 HP" },
    { label: "Transmisión", value: "Automática" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "5" },
    { label: "Colores", value: "Blanco · Negro · Gris" },
  ],
  "Sunray V6 Pasajeros": [
    { label: "Motor", value: "2.0L Turbo Euro V" },
    { label: "Potencia", value: "188 HP" },
    { label: "Transmisión", value: "Manual 6 velocidades" },
    { label: "Tracción", value: "4×2" },
    { label: "Pasajeros", value: "17" },
    { label: "Colores", value: "Blanco" },
  ],
  "Sunray V6 Carga": [
    { label: "Motor", value: "2.0L Turbo Euro V" },
    { label: "Potencia", value: "188 HP" },
    { label: "Transmisión", value: "Manual 6 velocidades" },
    { label: "Tracción", value: "4×2" },
    { label: "Carga máx.", value: "Consultar" },
    { label: "Colores", value: "Blanco" },
  ],

  // --- CAMIONES ---
  "X100 Ferretero": [
    { label: "Motor", value: "1.6L Gasolina Euro II" },
    { label: "Potencia", value: "118 HP" },
    { label: "Transmisión", value: "Manual 5V+R" },
    { label: "Carga", value: "1 Ton" },
    { label: "Combustible", value: "Gasolina" },
  ],
  "Urban 3 Ton": [
    { label: "Motor", value: "2.8L Diésel Euro II" },
    { label: "Potencia", value: "91 HP" },
    { label: "Transmisión", value: "Manual 5 velocidades" },
    { label: "Carga", value: "3 Ton" },
    { label: "Combustible", value: "Diésel" },
  ],
  "C 3500 Ferretero 4X4": [
    { label: "Motor", value: "2.8L Diésel Euro II" },
    { label: "Potencia", value: "91 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Tracción", value: "4×4" },
    { label: "Carga", value: "3.5 Ton" },
  ],
  "Doble Cabina Ferretero": [
    { label: "Motor", value: "2.8L Diésel Euro II" },
    { label: "Potencia", value: "91 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Carga", value: "Consultar" },
    { label: "Combustible", value: "Diésel" },
  ],
  "6T Ferretero": [
    { label: "Motor", value: "4.0L Diésel Euro II" },
    { label: "Potencia", value: "138 HP" },
    { label: "Transmisión", value: "Manual 6 velocidades" },
    { label: "Carga", value: "6 Ton" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Búfalo 12 Ton": [
    { label: "Motor", value: "Cummins C230-20" },
    { label: "Potencia", value: "230 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Carga", value: "12 Ton" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Búfalo XL": [
    { label: "Motor", value: "Cummins C230-20" },
    { label: "Potencia", value: "230 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Carga", value: "Consultar" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Leyenda 20 Ton": [
    { label: "Motor", value: "Diésel Euro II" },
    { label: "Potencia", value: "Consultar" },
    { label: "Transmisión", value: "Manual" },
    { label: "Carga", value: "20 Ton" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Cavalino": [
    { label: "Motor", value: "Diésel Euro II" },
    { label: "Potencia", value: "Consultar" },
    { label: "Transmisión", value: "Manual" },
    { label: "Carga", value: "Consultar" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Chuto 4251 430 HP": [
    { label: "Motor", value: "Weichai WP12.430" },
    { label: "Potencia", value: "430 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Carga", value: "45 Ton" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Minero 14M3": [
    { label: "Motor", value: "Yuchai YC6I200" },
    { label: "Potencia", value: "200 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Capacidad tolva", value: "14 M³" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Minero 20M3": [
    { label: "Motor", value: "Weichai WP10.340" },
    { label: "Potencia", value: "340 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Capacidad tolva", value: "20 M³" },
    { label: "Combustible", value: "Diésel" },
  ],

  // --- ELÉCTRICOS ---
  "Voltio Eléctrico": [
    { label: "Tipo", value: "100% Eléctrico" },
    { label: "Potencia", value: "Consultar" },
    { label: "Transmisión", value: "Automática" },
    { label: "Autonomía", value: "Consultar" },
    { label: "Pasajeros", value: "5" },
  ],
  "Electrón Eléctrico": [
    { label: "Tipo", value: "100% Eléctrico" },
    { label: "Potencia", value: "Consultar" },
    { label: "Transmisión", value: "Automática" },
    { label: "Autonomía", value: "Consultar" },
    { label: "Pasajeros", value: "5" },
  ],
  "Nevado Eléctrico": [
    { label: "Tipo", value: "100% Eléctrico" },
    { label: "Potencia", value: "Consultar" },
    { label: "Transmisión", value: "Automática" },
    { label: "Autonomía", value: "Consultar" },
    { label: "Pasajeros", value: "5" },
  ],
  "1073 Camión Eléctrico": [
    { label: "Tipo", value: "100% Eléctrico" },
    { label: "Potencia", value: "Consultar" },
    { label: "Transmisión", value: "Automática" },
    { label: "Carga", value: "Consultar" },
    { label: "Autonomía", value: "Consultar" },
  ],

  // --- UTILITARIOS ---
  "Sunray V4 Ambulancia": [
    { label: "Motor", value: "2.0L Turbo Euro V" },
    { label: "Potencia", value: "188 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Equipamiento", value: "Médico especializado" },
    { label: "Colores", value: "Blanco" },
  ],
  "Compactador 5 Ton": [
    { label: "Motor", value: "Cummins B125" },
    { label: "Potencia", value: "125 HP" },
    { label: "Transmisión", value: "Manual" },
    { label: "Capacidad", value: "5 M³" },
    { label: "Combustible", value: "Diésel" },
  ],
  "Urban Chasis Largo 3 Ton": [
    { label: "Motor", value: "2.8L Diésel Euro II" },
    { label: "Potencia", value: "91 HP" },
    { label: "Transmisión", value: "Manual 5 velocidades" },
    { label: "Carga", value: "3 Ton" },
    { label: "Combustible", value: "Diésel" },
  ],
  "M4 Carroza": [
    { label: "Motor", value: "2.0L Euro V" },
    { label: "Potencia", value: "145 HP" },
    { label: "Transmisión", value: "Manual 6 velocidades" },
    { label: "Pasajeros", value: "11" },
    { label: "Combustible", value: "Gasolina" },
  ],
};

export default specs;
