export const WHATSAPP_NUMBER = "584143200146";
export const WHATSAPP_DISPLAY = "+58 414 320 0146";
export const EMAIL = "rigobertomolina6@gmail.com";
export const INSTAGRAM = "https://www.instagram.com/ventasjacvzla/";
export const INSTAGRAM_HANDLE = "@ventasjacvzla";

export const waLink = (message?: string) =>
  `https://wa.me/${WHATSAPP_NUMBER}${message ? `?text=${encodeURIComponent(message)}` : ""}`;

export const waModelMessage = (model: string) =>
  `Hola Rigoberto, me interesa el ${model}. ¿Puedes darme más información?`;

/* ── Specs interface ── */
export interface CarSpecs {
  motor?: string;
  potencia?: string;
  torque?: string;
  combustible?: string;
  transmisionDetalle?: string;
  suspension?: string[];
  frenos?: string;
  dimensiones?: string;
  pesoNeto?: string;
  capacidadCarga?: string;
  tanque?: string;
  seguridad?: string[];
  tecnologia?: string[];
  equipamiento?: string[];
}

/* ── Model interface ── */
export interface CarModel {
  name: string;
  tagline: string;
  transmission: string;
  traction: string;
  colors?: { name: string; hex: string }[];
  price?: string;
  priceDirecta?: string;
  priceFacil?: string;
  featured?: string;
  specs?: CarSpecs;
  image?: string;
  referentialImage?: boolean;
}

/* ══════════════════════════════════════════
   Comerciales Livianos (PRIORIDAD)
   ══════════════════════════════════════════ */
export const commercialModels: CarModel[] = [
  {
    name: "X100 FERRETERO",
    tagline: "Carga ligera urbana — ágil y económico · 1.6 Ton",
    transmission: "Manual",
    traction: "4x2",
    price: "$2.489,1",
    priceDirecta: "desde $2.489/mes",
    priceFacil: "desde $1.197/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/X100-FERRETERO-1024x427.webp",
    featured: "COMERCIAL MÁS CONSULTADO",
    specs: {
      motor: "1.6 L Gasolina Euro II WT",
      potencia: "118 Hp",
      torque: "155 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Manual LCST18 MT — 5 velocidades",
      suspension: ["Delantera: Ballesta 3", "Trasera: Ballesta 3+2"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS",
      dimensiones: "5.182 x 1.700 x 2.070 mm",
      pesoNeto: "1.570 kg",
      capacidadCarga: "1.6 Ton",
      tanque: "60 L",
      seguridad: ["ABS", "Cinturón de seguridad 3 puntos", "Bloqueo central", "Dirección asistida"],
      equipamiento: ["Neumáticos 175/75R16 8PR", "Rin de hierro", "Lámpara eléctrica"],
    },
  },
  {
    name: "URBAN FERRETERO 3 TON",
    tagline: "Distribución urbana — capacidad de 3 toneladas",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.630,0",
    priceDirecta: "desde $3.630/mes",
    priceFacil: "desde $1.798/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/URBAN-FERRETERO-1024x427.webp",
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC5T255M3 MT — 5 velocidades",
      suspension: ["Trasera: Ballesta con amortiguador telescópico y auxiliar 5+3"],
      frenos: "Disco (del.) / Tambor hidráulico (tras.)",
      dimensiones: "5.445 x 1.952 x 2.300 mm",
      pesoNeto: "1.920 kg",
      capacidadCarga: "3 Ton",
      tanque: "85 L",
      seguridad: ["Dirección asistida", "Alarma de marcha atrás", "Freno de motor", "Cinturón ajustable"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16 12PR", "Rin de hierro", "Ventana manual"],
    },
  },
  {
    name: "URBAN CHASIS LARGO 3 TON",
    tagline: "Chasis largo para carrocerías especiales",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.427,3",
    priceDirecta: "desde $3.427/mes",
    priceFacil: "desde $1.692/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/Urban-Chasis-1024x576.webp",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
    ],
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LCST255M3 MT — 5 velocidades",
      suspension: ["Trasera: Ballesta con amortiguador telescópico y auxiliar 5+3"],
      frenos: "Disco (del.) / Tambor hidráulico (tras.)",
      dimensiones: "5.445 x 1.952 x 2.300 mm",
      pesoNeto: "1.920 kg",
      capacidadCarga: "3 Ton",
      tanque: "85 L",
      seguridad: ["Dirección asistida", "Alarma de marcha atrás", "Freno de escape opcional", "Cinturón ajustable"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16 12PR", "Rin de hierro", "Ventana manual"],
    },
  },
  {
    name: "SUNRAY V6",
    tagline: "Van de carga o pasajeros — versatilidad total",
    transmission: "Manual",
    traction: "4x2",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/SUNRAY-V6-171-1024x427.webp",
    priceDirecta: "desde $5.945/mes",
    priceFacil: "desde $2.785/mes",
    specs: {
      motor: "2.8 L Turbo Diésel",
      combustible: "Diésel",
      transmisionDetalle: "Manual — 5 velocidades",
    },
  },
  {
    name: "M4 CARROZA",
    tagline: "Transporte colectivo — hasta 16 pasajeros",
    transmission: "Manual",
    traction: "4x2",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/SUNRAY-V6-171-1024x427.webp",
    priceDirecta: "desde $6.386/mes",
    priceFacil: "desde $3.875/mes",
    referentialImage: true,
    specs: {
      combustible: "Diésel",
    },
  },
];

/* ══════════════════════════════════════════
   Camiones
   ══════════════════════════════════════════ */
export const truckModels: CarModel[] = [
  {
    name: "6T CHASIS 6 TON",
    tagline: "Camión mediano para carga de 6 toneladas · Toma de fuerza PTO",
    transmission: "Manual",
    traction: "4x2",
    price: "$4.905,3",
    priceDirecta: "desde $4.905/mes",
    priceFacil: "desde $2.471/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/6T-FERRETERO-1024x425.webp",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
    ],
    specs: {
      motor: "CUMMINS B-140-33 · 4.0 L Diésel Euro II",
      potencia: "138 Hp",
      torque: "502 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC6T540B MT — 6 velocidades + Toma de fuerza PTO",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico / Barra estabilizadora"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "7.411 x 2.186 x 2.354 mm",
      pesoNeto: "3.660 kg",
      capacidadCarga: "6 Ton",
      tanque: "200 L",
      seguridad: ["Protección del radiador", "Cinturones de seguridad", "Alarma de marcha atrás"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 215/75R17.5", "Rin de hierro", "Caja de carga (litera)"],
    },
  },
  {
    name: "6T FERRETERO 6 TON",
    tagline: "Camión ferretero con caja de 6 toneladas · CUMMINS",
    transmission: "Manual",
    traction: "4x2",
    price: "$5.270,2",
    priceDirecta: "desde $5.270/mes",
    priceFacil: "desde $2.664/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/6T-FERRETERO-1024x425.webp",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
    ],
    specs: {
      motor: "CUMMINS B140-33 · 4.0 L Diésel Euro II",
      potencia: "138 Hp",
      torque: "502 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC6T540B — 6 velocidades",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico / Barra estabilizadora", "Trasera: Resorte ballesta sobre eje rígido"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "7.411 x 2.186 x 2.354 mm",
      pesoNeto: "3.660 kg",
      capacidadCarga: "6 Ton",
      tanque: "200 L",
      seguridad: ["Cinturones de seguridad", "Alarma de marcha atrás", "Luces de circulación diurna"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 215/75R17.5", "Rin de hierro", "Protección del radiador", "Faros antiniebla", "Caja de carga (litera)"],
    },
  },
  {
    name: "BÚFALO 12 TON",
    tagline: "Camión pesado CUMMINS — 12 Ton · Tanque 1000 L",
    transmission: "Manual",
    traction: "4x2",
    price: "$7.541,7",
    priceDirecta: "desde $7.541/mes",
    priceFacil: "desde $3.862/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/BUFALO-1024x425.webp",
    colors: [
      { name: "Rojo", hex: "#dc2626" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Gris", hex: "#9ca3af" },
    ],
    specs: {
      motor: "CUMMINS C230-20 · 8.3 L Diésel Euro II",
      potencia: "230 Hp",
      torque: "861 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 83S105TA — 8 velocidades · Toma de fuerza PTO",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico", "Trasera: Resorte ballesta sobre eje rígido"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "8.710 x 2.350 x 3.019 mm",
      pesoNeto: "5.780 kg",
      capacidadCarga: "12 Ton",
      tanque: "1.000 L",
      seguridad: ["Parachoques delantero inferior y trasero", "Freno auxiliar de escape", "Luces de circulación diurna", "Alarma de marcha atrás", "Cubierta protectora del faro trasero"],
      equipamiento: ["Neumáticos 11R22.5", "Rin de aluminio", "Faros antiniebla", "Visera solar", "Volteo eléctrico", "Aire acondicionado"],
    },
  },
  {
    name: "BÚFALO XL 13 TON",
    tagline: "Chasis extra largo 9.2 mt carrozable · CUMMINS · Toma de fuerza PTO",
    transmission: "Manual",
    traction: "4x2",
    price: "$7.932,8",
    priceDirecta: "desde $7.932/mes",
    priceFacil: "desde $4.068/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/BUFALO-1024x425.webp",
    colors: [
      { name: "Rojo", hex: "#dc2626" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Gris", hex: "#9ca3af" },
    ],
    specs: {
      motor: "CUMMINS C230-20 · 8.3 L Diésel Euro II",
      potencia: "230 Hp",
      torque: "1.050 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 83S105TA — 8 velocidades · Toma de fuerza PTO",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico", "Trasera: Resorte ballesta sobre eje rígido"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "11.825 x 2.520 x 3.025 mm",
      pesoNeto: "6.300 kg",
      capacidadCarga: "13 Ton",
      tanque: "600 + 600 L",
      seguridad: ["Parachoques delantero inferior y trasero", "Freno auxiliar de escape", "Luces de circulación diurna", "Alarma de marcha atrás", "Cubierta protectora del faro trasero"],
      equipamiento: ["Neumáticos 11R22.5", "Rin de aluminio", "Visera solar", "Volteo eléctrico", "Aire acondicionado", "Vidrios eléctricos"],
    },
  },
  {
    name: "LEYENDA 340HP",
    tagline: "Camión pesado WEICHAI 340HP — 20 Ton · Tanque 1.225 L",
    transmission: "Manual",
    traction: "4x2",
    price: "$10.853,3",
    priceDirecta: "desde $10.853/mes",
    priceFacil: "desde $5.609/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/LEYENDA-1024x425.webp",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "WEICHAI WP10.340 E22 · 9.8 L Diésel Euro II",
      potencia: "340 Hp",
      torque: "1.400 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 9JSD150T-B — 8 velocidades + 1R · Toma de fuerza PTO",
      suspension: ["Delantera: Ballesta 10/12", "Trasera: Resorte ballesta 10/12"],
      frenos: "Disco",
      dimensiones: "10.990 x 2.495 x 3.450 mm",
      pesoNeto: "9.620 kg",
      capacidadCarga: "20 Ton",
      tanque: "1.225 L",
      seguridad: ["Freno auxiliar de escape", "Barra estabilizadora de eje trasero", "Alarma de marcha atrás", "Cubierta protectora del faro trasero", "Caja de herramientas del chasis"],
      tecnologia: ["Radio y MP3"],
      equipamiento: ["Neumáticos 12.00R22.5", "Rin de aluminio", "Visera solar", "Cabina abatible", "Ventanas eléctricas", "Espejo retrovisor mecánico", "Aire acondicionado"],
    },
  },
  {
    name: "LEYENDA 380HP",
    tagline: "Camión pesado WEICHAI 380HP — 20 Ton · Acople para remolque",
    transmission: "Manual",
    traction: "4x2",
    price: "$12.003,0",
    priceDirecta: "desde $12.003/mes",
    priceFacil: "desde $6.215/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/LEYENDA-1024x425.webp",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
    ],
    specs: {
      motor: "WEICHAI WP10.380 E22 · 9.8 L Diésel Euro II",
      potencia: "380 Hp",
      torque: "1.550 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 12JSD160T — 12 velocidades + 1R · Toma de fuerza PTO",
      suspension: ["Delantera: Ballesta 10/12", "Trasera: Resorte ballesta 10/12"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "10.990 x 2.550 x 3.305 mm",
      pesoNeto: "9.620 kg",
      capacidadCarga: "20 Ton",
      tanque: "1.225 L",
      seguridad: ["Freno auxiliar de escape", "Barra estabilizadora de eje trasero", "Alarma de marcha atrás", "Cubierta protectora del faro trasero", "Caja de herramientas del chasis"],
      tecnologia: ["Radio y MP3"],
      equipamiento: ["Neumáticos 12.00R22.5", "Rin de aluminio", "Visera solar", "Cabina abatible", "Ventanas eléctricas", "Espejo retrovisor mecánico", "Aire acondicionado"],
    },
  },
  {
    name: "CAVALINO 22 TON",
    tagline: "Chuto sencillo WEICHAI — 22 toneladas · Toma de fuerza PTO",
    transmission: "Manual",
    traction: "4x2",
    price: "$7.606,2",
    priceDirecta: "desde $7.606/mes",
    priceFacil: "desde $3.896/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/CAVALINO-1024x425.webp",
    colors: [
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "WEICHAI WP6.240E32 · 6.8 L Diésel Euro II",
      potencia: "240 Hp",
      torque: "900 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 83S105TA — 8 velocidades",
      suspension: ["Delantera: Ballesta parabólica 10/9+7", "Trasera: Resorte ballesta parabólica 10/9+7"],
      frenos: "ABS / Tambor (tras.)",
      dimensiones: "6.010 x 2.495 x 2.990 mm",
      pesoNeto: "5.200 kg",
      capacidadCarga: "22 Ton",
      tanque: "600 L",
      seguridad: ["Freno auxiliar de escape", "Faros LED", "Grabadora de conducción", "Alarma de marcha atrás"],
      equipamiento: ["Neumáticos 10R22.5 16PR", "Rin de aluminio", "Visera solar", "Cabina abatible", "Vidrios eléctricos", "Aire acondicionado"],
    },
  },
  {
    name: "CHUTO 400HP 40 TON",
    tagline: "Tracto-camión pesado — 400 HP y 40 toneladas",
    transmission: "Manual",
    traction: "6x4",
    price: "$10.249,3",
    priceDirecta: "desde $10.249/mes",
    priceFacil: "desde $5.290/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/CHUTO-4251-430-1024x425.webp",
    specs: {
      motor: "10.3 L Diésel Euro II",
      potencia: "400 Hp @ 1.900 RPM",
      torque: "1.800 Nm",
      combustible: "Diésel",
      transmisionDetalle: "12JSD180T — 12 velocidades",
      suspension: ["Delantera: Ballesta 10 piezas con barra", "Trasera: Resorte ballesta 12 piezas con barra"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "6.915 x 2.522 x 3.611 mm",
      pesoNeto: "9.382 kg",
      capacidadCarga: "40 Ton",
      tanque: "400 L",
      seguridad: ["Freno auxiliar de escape", "Alarma de marcha atrás"],
      tecnologia: ["Radio/MP3"],
      equipamiento: ["Neumáticos 12R22.5 / 13R22.5 18PR", "Cabina abatible", "Visera solar", "Ventana eléctrica"],
    },
  },
  {
    name: "K5 CHUTO 430HP 45 TON",
    tagline: "El más potente — WEICHAI 430 HP, 45 toneladas",
    transmission: "Manual",
    traction: "6x4",
    price: "$11.960,6",
    priceDirecta: "desde $11.960/mes",
    priceFacil: "desde $6.193/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/CHUTO-4251-430-1024x425.webp",
    colors: [
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "WEICHAI WP12.430E201 · 11.6 L Diésel Euro II",
      potencia: "430 Hp",
      torque: "2.000 Nm",
      combustible: "Diésel",
      transmisionDetalle: "12JSD200TA.B — 12 velocidades + 2R",
      suspension: ["Delantera: Ballesta 10 piezas", "Trasera: Resorte ballesta 12 piezas"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "6.815 x 2.495 x 3.713 mm",
      pesoNeto: "9.446 kg",
      capacidadCarga: "45 Ton",
      tanque: "900 L",
      seguridad: ["Freno auxiliar de escape", "Luces de circulación diurna", "Alarma de marcha atrás"],
      equipamiento: ["Neumáticos 315/80R22.5 20PR", "Cabina abatible eléctrica", "Retrovisor mecánico", "Escalera mecánica", "Aire acondicionado"],
    },
  },
  {
    name: "MINERO 14M3",
    tagline: "Volqueta minera 14 m³ — YUCHAI 200HP · 10 Ton",
    transmission: "Manual",
    traction: "6x4",
    price: "$10.669,1",
    priceDirecta: "desde $10.669/mes",
    priceFacil: "desde $5.512/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/CHUTO-4251-430-1024x425.webp",
    referentialImage: true,
    colors: [
      { name: "Amarillo", hex: "#facc15" },
      { name: "Blanco", hex: "#f5f5f5" },
    ],
    specs: {
      motor: "YUCHAI YC6J200 · 6.5 L Diésel Euro II",
      potencia: "200 Hp",
      torque: "700 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 8JS105T — 8 velocidades + 1R · Toma de fuerza PTO",
      suspension: ["Delantera: Ballesta parabólica 9/12+9", "Trasera: Ballesta parabólica 9/12+9"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "6.973 x 2.503 x 3.120 mm",
      pesoNeto: "9.010 kg",
      capacidadCarga: "10 Ton · Tolva 14 m³",
      tanque: "200 L",
      seguridad: ["Alarma de marcha atrás", "Freno auxiliar de escape"],
      tecnologia: ["Radio + MP3"],
      equipamiento: ["Neumáticos 10.00R20 18PR", "Rin de hierro", "Vidrios eléctricos", "Aire acondicionado"],
    },
  },
  {
    name: "MINERO 20M3",
    tagline: "Volqueta minera 20 m³ — WEICHAI 340HP · 20 Ton",
    transmission: "Manual",
    traction: "6x4",
    price: "$14.109,6",
    priceDirecta: "desde $14.109/mes",
    priceFacil: "desde $7.327/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/CHUTO-4251-430-1024x425.webp",
    referentialImage: true,
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Gris", hex: "#9ca3af" },
    ],
    specs: {
      motor: "WEICHAI WP10.340 E22 · 9.8 L Diésel Euro II",
      potencia: "340 Hp",
      torque: "1.400 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 12JSD160T MT — 12 velocidades + 2R · Toma de fuerza PTO",
      suspension: ["Delantera: Ballesta 10 piezas", "Trasera: Ballesta 12 piezas"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "8.345 x 2.530 x 3.280 mm",
      pesoNeto: "9.573 kg",
      capacidadCarga: "20 Ton · Tolva 20 m³",
      tanque: "400 L",
      seguridad: ["Alarma de marcha atrás", "Protector del motor", "Marco de protección del radiador", "Freno auxiliar de escape"],
      tecnologia: ["Radio + MP3"],
      equipamiento: ["Neumáticos 12R22.5", "Rin de aluminio", "Vidrios eléctricos", "Aire acondicionado", "Cerradura con control", "Visera solar", "Cabina abatible"],
    },
  },
  {
    name: "MINERO 28M3",
    tagline: "Volqueta minera 28 m³ — WEICHAI 380HP · 28 Ton",
    transmission: "Manual",
    traction: "6x4",
    price: "$18.152,5",
    priceDirecta: "desde $18.152/mes",
    priceFacil: "desde $9.459/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/03/CHUTO-4251-430-1024x425.webp",
    referentialImage: true,
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Verde", hex: "#16a34a" },
    ],
    specs: {
      motor: "WEICHAI WP10.380 E22 · 9.8 L Diésel Euro II",
      potencia: "380 Hp",
      torque: "1.600 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 12JSD160T MT — 12 velocidades + 2R",
      suspension: ["Delantera: Ballesta 10 piezas", "Trasera: Ballesta 12 piezas"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "10.825 x 2.560 x 3.350 mm",
      pesoNeto: "10.293 kg",
      capacidadCarga: "28 Ton · Tolva 28 m³",
      tanque: "400 L",
      seguridad: ["Alarma de marcha atrás", "Protector del motor", "Marco de protección del radiador", "Freno auxiliar de escape"],
      tecnologia: ["Radio + MP3"],
      equipamiento: ["Neumáticos 12R22.5", "Rin de hierro", "Vidrios eléctricos", "Aire acondicionado", "Cerradura con control", "Visera solar", "Cabina abatible"],
    },
  },
];

/* ══════════════════════════════════════════
   Pickups / Camionetas
   ══════════════════════════════════════════ */
export const pickupModels: CarModel[] = [
  {
    name: "LA VENEZOLANA 4X2",
    tagline: "La pickup que trabaja tan duro como tú · Gasolina",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.319,9",
    priceDirecta: "desde $3.319/mes",
    priceFacil: "desde $1.635/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/T6-la-venezolana-de-jac-motors-venezuela-1024x427.jpg",
    colors: [
      { name: "Azul", hex: "#2563eb" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "2.0 L WT Euro V",
      potencia: "145 Hp",
      torque: "190 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Manual LCST80 — 5 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.760 kg",
      capacidadCarga: "820 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Sensor de estacionamiento trasero", "Bloqueo de seguridad para niños"],
      tecnologia: ["Radio/MP3", "Bluetooth", "4 altavoces", "Control crucero"],
      equipamiento: ["Neumáticos 245/65R17", "Rines de aluminio", "Asientos de ecopiel", "Escalones laterales"],
    },
  },
  {
    name: "LA VENEZOLANA 4X2 DIESEL",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/02/jac_banners_la_venezolana_diesel_4x2_4x4-1024x427.jpg",
    tagline: "Mayor eficiencia diésel para trabajo pesado",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.423,4",
    priceDirecta: "desde $3.423/mes",
    priceFacil: "desde $1.690/mes",
    colors: [
      { name: "Azul", hex: "#2563eb" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Blanco", hex: "#f5f5f5" },
    ],
    specs: {
      motor: "2.8 L WT Turbo Euro II",
      potencia: "137 Hp",
      torque: "210 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC5T80 — 5 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.815 kg",
      capacidadCarga: "900 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Sensor de estacionamiento trasero", "Bloqueo de seguridad para niños"],
      tecnologia: ["Radio/MP3", "Bluetooth", "4 altavoces"],
      equipamiento: ["Neumáticos 245/65R17", "Rines de aluminio", "Asientos de ecopiel", "Escalones laterales"],
    },
  },
  {
    name: "LA VENEZOLANA 4X4 DIESEL",
    tagline: "Potencia diésel y tracción total sin compromiso",
    transmission: "Manual",
    traction: "4x4",
    price: "$3.828,0",
    priceDirecta: "desde $3.828/mes",
    priceFacil: "desde $1.903/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/02/jac_banners_la_venezolana_diesel_4x2_4x4-1024x427.jpg",
    colors: [
      { name: "Azul", hex: "#2563eb" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Blanco", hex: "#f5f5f5" },
    ],
    specs: {
      motor: "2.8 L WT Turbo Euro I",
      potencia: "137 Hp",
      torque: "210 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC6T32 — 6 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.930 kg",
      capacidadCarga: "900 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Bloqueo de seguridad para niños", "Cerradura eléctrica"],
      equipamiento: ["Neumáticos 245/65R17", "Rines de aluminio", "Asientos de ecopiel", "Escalones laterales"],
    },
  },
  {
    name: "LA VENEZOLANA PRO 4X4",
    tagline: "La versión premium 2.0 Turbo + BELJIMMY 125",
    transmission: "Manual",
    traction: "4x4",
    price: "$4.522,3",
    priceDirecta: "desde $4.522/mes",
    priceFacil: "desde $2.269/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/06/jac_banners_la_venezolana_pro-1-1024x427.jpg",
    specs: {
      motor: "2.0 L Turbo Euro V (enfriador interno)",
      potencia: "188 Hp",
      torque: "320 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Manual LC6T32 — 6 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Disco (tras.) · ABS+EBD",
      dimensiones: "5.325 x 1.880 x 1.830 mm",
      pesoNeto: "1.940 kg",
      capacidadCarga: "900 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "TPMS", "Arranque inteligente", "Bloqueo de seguridad para niños"],
      tecnologia: ["Sensor de estacionamiento trasero"],
      equipamiento: ["Neumáticos 265/60R18", "Rines de aluminio", "Luces LED DRL", "Escalones laterales", "Incluye BELJIMMY 125 (moto 125cc)"],
    },
  },
  {

    name: "T5 LA VENEZOLANA 4X2 DIESEL",
    tagline: "Diésel 2.8L de 145 Hp con 1.000 kg de carga",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.388,6",
    priceDirecta: "desde $3.388/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/02/jac_banners_la_venezolana_diesel_4x2_4x4-1024x427.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "2.8 L VVT Euro V",
      potencia: "145 Hp",
      torque: "190 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC5T80 MT — 5 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.720 kg",
      capacidadCarga: "1.000 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Sensor de estacionamiento trasero", "Cerradura eléctrica con bloqueo automático"],
      tecnologia: ["Radio/MP3", "Bluetooth", "2 altavoces", "Toma 12v frontal"],
      equipamiento: ["Neumáticos 245/65R17", "Rines de aluminio", "Asientos de tela", "Escalones laterales", "Cajón 2.260 x 1.520 x 470 mm"],
    },
  },
  {
    name: "LA VENEZOLANA PAL CAMPO 4X4",
    tagline: "Plataforma de metal con barandas de madera · 4x4 diésel",
    transmission: "Manual",
    traction: "4x4",
    price: "$4.313,8",
    priceDirecta: "desde $4.313/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/02/jac_banners_la_venezolana_diesel_4x2_4x4-1024x427.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Azul", hex: "#2563eb" },
    ],
    specs: {
      motor: "2.8 L VVT Turbo Euro II",
      potencia: "137 Hp",
      torque: "210 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC6T32 — 6 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.930 kg",
      capacidadCarga: "800 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Sensor de estacionamiento trasero", "Bloqueo de seguridad para niños"],
      tecnologia: ["Radio/MP3", "Bluetooth", "4 altavoces", "Toma 12v frontal"],
      equipamiento: ["Neumáticos 265/70R17", "Rines de aluminio", "Plataforma de metal con barandas de madera 1,62 x 1,62 m", "2 espacios para cajas de herramientas", "Peto protector de motor", "Tiro de remolque"],
    },
  },
  {

    name: "DOBLE CABINA",
    tagline: "Pickup doble cabina diésel — 3 Ton de carga",
    transmission: "Manual",
    traction: "4x2",
    price: "$4.056,4",
    priceDirecta: "desde $4.056/mes",
    priceFacil: "desde $2.023/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/DOBLE-CABINA-FERRETERO-1024x427.webp",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
    ],
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC5T255M3 MT — 5 velocidades",
      suspension: ["Delantera: Ballestas delanteras 7", "Trasera: Ballestas traseras 4+6"],
      frenos: "Disco (del.) / Tambor (tras.)",
      dimensiones: "6.045 x 1.900 x 2.370 mm",
      pesoNeto: "2.560 kg",
      capacidadCarga: "3 Ton",
      tanque: "100 L",
      seguridad: ["Advertencia cinturón de seguridad", "Alarma de marcha atrás", "Cinturón regulable en altura"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16", "Rin de hierro", "Ventanas eléctricas", "Asientos de tela"],
    },
  },
  {
    name: "C-3500 4X4",
    tagline: "Robusta y confiable · 3.5 Ton · Tracción 4x4",
    transmission: "Manual",
    traction: "4x4",
    price: "$4.958,5",
    priceDirecta: "desde $4.958/mes",
    priceFacil: "desde $2.499/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/C-3500-FERRETERO-4X4-1024x427.webp",
    colors: [
      { name: "Gris", hex: "#9ca3af" },
    ],
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LCST255M3 MT — 5 velocidades · Tracción 4x4",
      suspension: ["Delantera: Ballesta con amortiguador telescópico", "Trasera: Ballesta con amortiguador telescópico y auxiliar"],
      frenos: "Tambor hidráulico (del.) / Tambor hidráulico (tras.)",
      dimensiones: "5.445 x 1.952 x 2.300 mm",
      pesoNeto: "1.920 kg",
      capacidadCarga: "3.5 Ton",
      tanque: "85 L",
      seguridad: ["Dirección asistida", "Alarma de marcha atrás", "Freno de motor", "Cinturón ajustable"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16 12PR", "Rin de hierro", "Ventana manual"],
    },
  },
  {
    name: "AVENTURA",
    tagline: "Pickup premium 231 HP · 4 modos de manejo · BELJIMMY 125",
    transmission: "Automática",
    traction: "4x4",
    price: "$5.510,0",
    priceDirecta: "desde $5.510/mes",
    priceFacil: "desde $2.790/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/t9-Aventura-Gasolina-jac-motors-venezuela-1024x427.jpg",
    colors: [
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "2.0 L Turbo Inyección Euro II",
      potencia: "231 Hp",
      torque: "380 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Automático AT A8R50 — 8 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "ABS + EBD",
      dimensiones: "5.330 x 1.965 x 1.920 mm",
      pesoNeto: "2.055 kg",
      capacidadCarga: "1.000 kg",
      tanque: "150 L",
      seguridad: ["2 airbags frontales", "TPMS", "Arranque inteligente", "Sensores delantero/trasero", "Cámara 360°", "Bloqueo de seguridad para niños", "Bloqueador de diferencial trasero"],
      tecnologia: ["Pantalla táctil 10,4\"", "Apple CarPlay / Android Auto", "Bluetooth", "Carga inalámbrica", "USB trasero", "6 altavoces"],
      equipamiento: ["Neumáticos 265/60R18", "Rines de aluminio", "Techo corredizo eléctrico", "Rieles de techo", "4 modos: Normal, Eco, Snow, Sport", "Incluye BELJIMMY 125 (moto 125cc)"],
    },
  },
  {
    name: "PICKUP LIMITED",
    tagline: "Pickup automática premium · Bloqueador diferencial trasero · BELJIMMY 125",
    transmission: "Automática",
    traction: "4x4",
    price: "$5.601,1",
    priceDirecta: "desde $5.601/mes",
    priceFacil: "desde $2.838/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/t9-Aventura-Gasolina-jac-motors-venezuela-1024x427.jpg",
    referentialImage: true,
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Rojo", hex: "#dc2626" },
    ],
    specs: {
      motor: "2.0 L Turbo Inyección Euro V",
      potencia: "231 Hp",
      torque: "380 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Automático — 8 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Disco (tras.) · ABS + EBD",
      dimensiones: "5.330 x 1.965 x 1.920 mm",
      pesoNeto: "2.055 kg",
      capacidadCarga: "1.000 kg",
      tanque: "150 L",
      seguridad: ["2 airbags frontales", "TPMS", "Arranque inteligente", "Sensores delantero/trasero", "Cámara 360°", "Bloqueador de diferencial trasero"],
      tecnologia: ["Pantalla táctil", "Apple CarPlay / Android Auto", "Bluetooth", "6 altavoces"],
      equipamiento: ["Neumáticos 265/60R18", "Rines de aluminio", "Techo corredizo eléctrico", "Incluye BELJIMMY 125 (moto 125cc)"],
    },
  },
  {
    name: "AVENTURA PRO",
    tagline: "Edición Limitada OFF-ROAD · Winche + Snorkel · BELJIMMY 200",
    transmission: "Automática",
    traction: "4x4",
    price: "$6.813,3",
    priceDirecta: "desde $6.813/mes",
    priceFacil: "desde $3.478/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/10/jac_banners_aventura_pro_edicion_limitada-1024x427.jpg",
    colors: [
      { name: "Verde Oscuro", hex: "#1a3a1a" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Gris Plomo", hex: "#6b7280" },
      { name: "Gris Cemento", hex: "#9ca3af" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "2.0 L Turbo Inyección Euro II",
      potencia: "231 Hp",
      torque: "380 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Automático AT A8R50 — 8 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Disco (tras.) · ABS + EBD",
      dimensiones: "5.330 x 1.965 x 1.920 mm",
      pesoNeto: "2.055 kg",
      capacidadCarga: "1.000 kg",
      tanque: "150 L",
      seguridad: ["2 airbags frontales", "TPMS", "Arranque inteligente", "Sensores delantero/trasero", "Cámara 360°"],
      tecnologia: ["Pantalla táctil 10,4\"", "Apple CarPlay / Android Auto", "Bluetooth", "Carga inalámbrica", "6 altavoces"],
      equipamiento: ["Neumáticos 265/60R18", "Rines de aluminio", "Techo corredizo eléctrico", "Winche", "Snorkel", "Suspensión reforzada", "Mesetas reforzadas", "Rines reforzados", "Incluye BELJIMMY 200 (quad 180cc)"],
    },
  },
];

/* ══════════════════════════════════════════
   SUVs
   ══════════════════════════════════════════ */
export const suvModels: CarModel[] = [
  {
    name: "NEVADO MT",
    tagline: "El SUV familiar más completo del catálogo",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.351,6",
    priceDirecta: "desde $3.352/mes",
    priceFacil: "desde $1.655/mes",
    featured: "MÁS CONSULTADO",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/vehiculo-nevado-js4-de-jac-motors-venezuela-1024x427.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Azul", hex: "#2563eb" },
      { name: "Gris", hex: "#9ca3af" },
    ],
  },
  {
    name: "ARENA SPORT MT",
    tagline: "SUV compacto, perfecto para la ciudad",
    transmission: "Manual",
    traction: "4x2",
    price: "$2.568,3",
    priceDirecta: "desde $2.568/mes",
    priceFacil: "desde $1.242/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/09/jac_banners_arena_sport_mt-1024x427.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
    ],
  },
  {
    name: "ARENA SPORT AT",
    tagline: "Comodidad automática para el día a día",
    transmission: "Automática",
    traction: "4x2",
    price: "$2.775,3",
    priceDirecta: "desde $2.775/mes",
    priceFacil: "desde $1.351/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/09/jac_banners_arena_sport_at-1024x427.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
    ],
  },
  {
    name: "ARENA PRO XIP-4",
    tagline: "CVT automático con TPMS y faros LED",
    transmission: "Automática",
    traction: "4x2",
    price: "$3.040,5",
    priceDirecta: "desde $3.040/mes",
    priceFacil: "desde $1.491/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/jac_-motors_banners-Arena-Pro-1024x427.png",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
    ],
  },
  {
    name: "NEVADO AT",
    tagline: "Turbo automático con techo corredizo eléctrico",
    transmission: "Automática",
    traction: "4x2",
    price: "$3.715,2",
    priceDirecta: "desde $3.715/mes",
    priceFacil: "desde $2.677/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/nevado-automatico-2025-de-jac-motors-venezuela-1024x427.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Azul", hex: "#2563eb" },
    ],
  },
  {
    name: "ÉLITE",
    tagline: "Sedán premium 2.0 Turbo 231HP · Automático",
    transmission: "Automática",
    traction: "4x2",
    price: "$4.258,0",
    priceDirecta: "desde $4.258/mes",
    priceFacil: "desde $2.380/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/vehiculo-nevado-js4-de-jac-motors-venezuela-1024x427.jpg",
    referentialImage: true,
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
    ],
    specs: {
      motor: "2.0 L Turbo Euro V",
      potencia: "231 Hp",
      combustible: "Gasolina",
      transmisionDetalle: "Automática",
    },
  },
  {
    name: "GX7",
    tagline: "SUV premium · 180 HP Turbo 7DCT · Cámara 360°",
    transmission: "Automática",
    traction: "4x2",
    price: "$4.407,9",
    priceDirecta: "desde $4.407/mes",
    priceFacil: "desde $2.212/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2026/06/GX7-1-1.png",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris Oscuro", hex: "#4b5563" },
    ],
    specs: {
      motor: "1.5 L Turbo Euro V",
      potencia: "180 Hp",
      torque: "210 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "7DCT — 7 velocidades",
      seguridad: [
        "Airbags frontales y laterales",
        "Auto Hold",
        "TPMS",
        "Sensor de punto ciego",
        "Sensores de estacionamiento",
        "Cámara 360°",
      ],
      tecnologia: [
        "Pantalla táctil 10,4\"",
        "Apple CarPlay / Android Auto",
        "Carga inalámbrica",
      ],
      equipamiento: [
        "Rines de aluminio 18\"",
        "Techo panorámico",
        "Luces LED ajustables",
        "Asientos de ecopiel",
        "3 modos de manejo: Standard, Sport, Suave",
      ],
    },
  },
  {
    name: "TEPUY PRO",
    tagline: "SUV premium · 181 HP Turbo DCT · Pantalla 24,6\"",
    transmission: "Automática",
    traction: "4x2",
    price: "$4.594,5",
    priceDirecta: "desde $4.594/mes",
    priceFacil: "desde $2.311/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/06/jac_banners_tepuy_pro-1024x427.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Rojo", hex: "#dc2626" },
    ],
  },
  {
    name: "LITE 5",
    tagline: "SUV espacioso · 182 HP Turbo DCT · Maletero 1.253 L",
    transmission: "Automática",
    traction: "4x2",
    price: "$4.924,1",
    priceDirecta: "desde $4.924/mes",
    priceFacil: "desde $2.485/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/js8-Savanna-jac-motors-venezuela-1024x427.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
    ],
  },
  {
    name: "REFINE",
    tagline: "Van premium de pasajeros — confort y amplitud",
    transmission: "Automática",
    traction: "4x2",
    price: "$7.665,1",
    priceDirecta: "desde $7.665/mes",
    priceFacil: "desde $3.931/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/06/JAC-REFINE-EN-VENEZUELA-1024x427.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
  },
];
