export const WHATSAPP_NUMBER = "58XXXXXXXXXX";
export const WHATSAPP_DISPLAY = "+58 XXX XXXXXXX";
export const EMAIL = "correo@email.com";
export const INSTAGRAM = "https://www.instagram.com/ventasjacvzla/";
export const INSTAGRAM_HANDLE = "@ventasjacvzla";

export const waLink = (message?: string) =>
  `https://wa.me/${WHATSAPP_NUMBER}${message ? `?text=${encodeURIComponent(message)}` : ""}`;

export const waModelMessage = (model: string) =>
  `Hola Rigoberto, me interesa el ${model}. ¿Puedes darme más información?`;

/* ── Specs interface ── */
export interface CarSpecs {
  motor?: string;
  potencia?: string;
  torque?: string;
  combustible?: string;
  transmisionDetalle?: string;
  suspension?: string[];
  frenos?: string;
  dimensiones?: string;
  pesoNeto?: string;
  capacidadCarga?: string;
  tanque?: string;
  seguridad?: string[];
  tecnologia?: string[];
  equipamiento?: string[];
}

/* ── Model interface ── */
export interface CarModel {
  name: string;
  tagline: string;
  transmission: string;
  traction: string;
  colors?: { name: string; hex: string }[];
  price?: string;
  priceDirecta?: string;
  priceFacil?: string;
  featured?: string;
  specs?: CarSpecs;
  image?: string;
}

/* ══════════════════════════════════════════
   Comerciales Livianos (PRIORIDAD)
   ══════════════════════════════════════════ */
export const commercialModels: CarModel[] = [
  {
    name: "X100 FERRETERO",
    tagline: "Carga ligera urbana — ágil y económico · 1.6 Ton",
    transmission: "Manual",
    traction: "4x2",
    price: "$2.564,7",
    priceFacil: "desde $1.419/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/X100-FERRETERO-1024x427.webp",
    featured: "COMERCIAL MÁS CONSULTADO",
    specs: {
      motor: "1.6 L Gasolina Euro II WT",
      potencia: "118 Hp",
      torque: "155 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Manual LCST18 MT — 5 velocidades",
      suspension: ["Delantera: Ballesta 3", "Trasera: Ballesta 3+2"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS",
      dimensiones: "5.182 x 1.700 x 2.070 mm",
      pesoNeto: "1.570 kg",
      capacidadCarga: "1.6 Ton",
      tanque: "60 L",
      seguridad: ["ABS", "Cinturón de seguridad 3 puntos", "Bloqueo central", "Dirección asistida"],
      equipamiento: ["Neumáticos 175/75R16 8PR", "Rin de hierro", "Lámpara eléctrica"],
    },
  },
  {
    name: "URBAN FERRETERO 3 TON",
    tagline: "Distribución urbana — capacidad de 3 toneladas",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.395,2",
    priceFacil: "desde $1.791/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/URBAN-FERRETERO-1024x427.webp",
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC5T255M3 MT — 5 velocidades",
      suspension: ["Trasera: Ballesta con amortiguador telescópico y auxiliar 5+3"],
      frenos: "Disco (del.) / Tambor hidráulico (tras.)",
      dimensiones: "5.445 x 1.952 x 2.300 mm",
      pesoNeto: "1.920 kg",
      capacidadCarga: "3 Ton",
      tanque: "85 L",
      seguridad: ["Dirección asistida", "Alarma de marcha atrás", "Freno de motor", "Cinturón ajustable"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16 12PR", "Rin de hierro", "Ventana manual"],
    },
  },
  {
    name: "URBAN CHASIS LARGO 3 TON",
    tagline: "Chasis largo para carrocerías especiales",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.236,4",
    image: "urban-chasis-largo-3ton",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
    ],
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LCST255M3 MT — 5 velocidades",
      suspension: ["Trasera: Ballesta con amortiguador telescópico y auxiliar 5+3"],
      frenos: "Disco (del.) / Tambor hidráulico (tras.)",
      dimensiones: "5.445 x 1.952 x 2.300 mm",
      pesoNeto: "1.920 kg",
      capacidadCarga: "3 Ton",
      tanque: "85 L",
      seguridad: ["Dirección asistida", "Alarma de marcha atrás", "Freno de escape opcional", "Cinturón ajustable"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16 12PR", "Rin de hierro", "Ventana manual"],
    },
  },
  {
    name: "SUNRAY V6",
    tagline: "Van de carga o pasajeros — versatilidad total",
    transmission: "Manual",
    traction: "4x2",
    specs: {
      motor: "2.8 L Turbo Diésel",
      combustible: "Diésel",
      transmisionDetalle: "Manual — 5 velocidades",
    },
  },
  {
    name: "M4 CARROZA",
    tagline: "Transporte colectivo — hasta 16 pasajeros",
    transmission: "Manual",
    traction: "4x2",
    specs: {
      combustible: "Diésel",
    },
  },
];

/* ══════════════════════════════════════════
   Camiones
   ══════════════════════════════════════════ */
export const truckModels: CarModel[] = [
  {
    name: "6T CHASIS 6 TON",
    tagline: "Camión mediano para carga de 6 toneladas",
    transmission: "Manual",
    traction: "4x2",
    price: "$4.473,1",
    priceFacil: "desde $2.493/mes",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
    ],
    specs: {
      motor: "4.0 L Diésel Euro II",
      potencia: "138 Hp",
      torque: "502 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC6T540B MT — 6 velocidades",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico / Barra estabilizadora"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "7.411 x 2.186 x 2.354 mm",
      pesoNeto: "3.660 kg",
      capacidadCarga: "6 Ton",
      tanque: "200 L",
      seguridad: ["Cinturones de seguridad", "Alarma de marcha atrás"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 215/75R17.5", "Rin de hierro", "Ventana manual"],
    },
  },
  {
    name: "6T FERRETERO 6 TON",
    tagline: "Camión ferretero con caja de 6 toneladas · CUMMINS",
    transmission: "Manual",
    traction: "4x2",
    price: "$4.671,3",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
    ],
    specs: {
      motor: "CUMMINS B140-33 · 4.0 L Diésel Euro II",
      potencia: "138 Hp",
      torque: "502 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC6T540B — 6 velocidades",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico / Barra estabilizadora", "Trasera: Resorte ballesta sobre eje rígido"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "7.411 x 2.186 x 2.354 mm",
      pesoNeto: "3.660 kg",
      capacidadCarga: "6 Ton",
      tanque: "200 L",
      seguridad: ["Cinturones de seguridad", "Alarma de marcha atrás", "Luces de circulación diurna"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 215/75R17.5", "Rin de hierro", "Protección del radiador", "Caja de carga (litera)"],
    },
  },
  {
    name: "BÚFALO 12 TON",
    tagline: "Camión pesado CUMMINS — 12 Ton · Tanque 1000 L",
    transmission: "Manual",
    traction: "4x2",
    price: "$7.322,6",
    priceFacil: "desde $2.604/mes",
    colors: [
      { name: "Rojo", hex: "#dc2626" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Gris", hex: "#9ca3af" },
    ],
    specs: {
      motor: "CUMMINS C230-20 · 8.3 L Diésel Euro II",
      potencia: "230 Hp",
      torque: "861 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 83S105TA — 8 velocidades",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico", "Trasera: Resorte ballesta sobre eje rígido"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "8.710 x 2.350 x 3.019 mm",
      pesoNeto: "5.780 kg",
      capacidadCarga: "12 Ton",
      tanque: "1.000 L",
      seguridad: ["Parachoques delantero inferior y trasero", "Freno auxiliar de escape", "Luces de circulación diurna", "Alarma de marcha atrás"],
      equipamiento: ["Neumáticos 11R22.5", "Rin de aluminio", "Faros antiniebla", "Visera solar", "Volteo eléctrico"],
    },
  },
  {
    name: "BÚFALO XL 13 TON",
    tagline: "Chasis extra largo 9.5 mt carrozable · CUMMINS",
    transmission: "Manual",
    traction: "4x2",
    price: "$7.850,3",
    priceFacil: "desde $4.091/mes",
    specs: {
      motor: "CUMMINS C230-20 · 8.3 L Diésel Euro II",
      potencia: "230 Hp",
      torque: "861 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 83S105TA — 8 velocidades",
      suspension: ["Delantera: Ballesta sobre eje rígido / Amortiguador telescópico", "Trasera: Resorte ballesta sobre eje rígido"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "11.825 x 2.520 x 3.025 mm",
      pesoNeto: "6.300 kg",
      capacidadCarga: "13 Ton",
      seguridad: ["Parachoques delantero inferior y trasero", "Freno auxiliar de escape", "Luces de circulación diurna", "Alarma de marcha atrás"],
      equipamiento: ["Neumáticos 11R22.5", "Rin de aluminio", "Visera solar", "Volteo eléctrico", "Aire acondicionado", "Vidrios eléctricos"],
    },
  },
  {
    name: "LEYENDA 20 TON",
    tagline: "Camión de alto tonelaje WEICHAI — Tanque 1.225 L",
    transmission: "Manual",
    traction: "4x2",
    price: "$10.223,2",
    priceFacil: "desde $4.397/mes",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "WEICHAI WP10.340 E22 · 9.8 L Diésel Euro II",
      potencia: "340 Hp",
      torque: "1.400 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 90SD150T-B — 8 velocidades",
      suspension: ["Delantera: Ballesta 10/12", "Trasera: Resorte ballesta 10/12"],
      frenos: "Disco",
      dimensiones: "10.990 x 2.495 x 3.450 mm",
      pesoNeto: "9.620 kg",
      capacidadCarga: "20 Ton",
      tanque: "1.225 L",
      seguridad: ["Freno auxiliar de escape", "Barra estabilizadora de eje trasero", "Alarma de marcha atrás", "Cubierta protectora del faro trasero"],
      tecnologia: ["Radio y MP3"],
      equipamiento: ["Neumáticos 12.00R22.5", "Rin de aluminio", "Visera solar", "Cabina abatible"],
    },
  },
  {
    name: "CAVALINO 22 TON",
    tagline: "Chuto sencillo WEICHAI — 22 toneladas",
    transmission: "Manual",
    traction: "4x2",
    price: "$7.106,4",
    priceFacil: "desde $5.709/mes",
    colors: [
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "WEICHAI WP6.240E32 · 6.8 L Diésel Euro II",
      potencia: "240 Hp",
      torque: "900 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual 83S105TA — 8 velocidades",
      suspension: ["Delantera: Ballesta parabólica 10/9+7", "Trasera: Resorte ballesta parabólica 10/9+7"],
      frenos: "ABS / Tambor (tras.)",
      dimensiones: "6.010 x 2.495 x 2.990 mm",
      pesoNeto: "5.200 kg",
      capacidadCarga: "22 Ton",
      tanque: "600 L",
      seguridad: ["Freno auxiliar de escape", "Faros LED", "Grabadora de conducción", "Alarma de marcha atrás"],
      equipamiento: ["Neumáticos 10R22.5 16PR", "Rin de aluminio", "Visera solar", "Cabina abatible", "Vidrios eléctricos", "Aire acondicionado"],
    },
  },
  {
    name: "CHUTO 400HP 40 TON",
    tagline: "Tracto-camión pesado — 400 HP y 40 toneladas",
    transmission: "Manual",
    traction: "6x4",
    price: "$9.312,5",
    specs: {
      motor: "10.3 L Diésel Euro II",
      potencia: "400 Hp @ 1.900 RPM",
      torque: "1.800 Nm",
      combustible: "Diésel",
      transmisionDetalle: "12JSD180T — 12 velocidades",
      suspension: ["Delantera: Ballesta 10 piezas con barra", "Trasera: Resorte ballesta 12 piezas con barra"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "6.915 x 2.522 x 3.611 mm",
      pesoNeto: "9.382 kg",
      capacidadCarga: "40 Ton",
      tanque: "400 L",
      seguridad: ["Freno auxiliar de escape", "Alarma de marcha atrás"],
      tecnologia: ["Radio/MP3"],
      equipamiento: ["Neumáticos 12R22.5 / 13R22.5 18PR", "Cabina abatible", "Visera solar", "Ventana eléctrica"],
    },
  },
  {
    name: "K5 CHUTO 430HP 45 TON",
    tagline: "El más potente — WEICHAI 430 HP, 45 toneladas",
    transmission: "Manual",
    traction: "6x4",
    price: "$11.209,9",
    priceFacil: "desde $6.363/mes",
    colors: [
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "WEICHAI WP12.430E201 · 11.6 L Diésel Euro II",
      potencia: "430 Hp",
      torque: "2.000 Nm",
      combustible: "Diésel",
      transmisionDetalle: "12JSD200TA.B — 12 velocidades + 2R",
      suspension: ["Delantera: Ballesta 10 piezas", "Trasera: Resorte ballesta 12 piezas"],
      frenos: "Tambor (del.) / Tambor (tras.)",
      dimensiones: "6.815 x 2.495 x 3.713 mm",
      pesoNeto: "9.446 kg",
      capacidadCarga: "45 Ton",
      tanque: "900 L",
      seguridad: ["Freno auxiliar de escape", "Luces de circulación diurna", "Alarma de marcha atrás"],
      equipamiento: ["Neumáticos 315/80R22.5 20PR", "Cabina abatible eléctrica", "Retrovisor mecánico", "Escalera mecánica", "Aire acondicionado"],
    },
  },
];

/* ══════════════════════════════════════════
   Pickups / Camionetas
   ══════════════════════════════════════════ */
export const pickupModels: CarModel[] = [
  {
    name: "LA VENEZOLANA 4X2",
    tagline: "La pickup que trabaja tan duro como tú · Gasolina",
    transmission: "Manual",
    traction: "4x2",
    price: "$2.972,3",
    priceDirecta: "desde $2.972/mes",
    priceFacil: "desde $1.653/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/T6-la-venezolana-de-jac-motors-venezuela.jpg",
    colors: [
      { name: "Azul", hex: "#2563eb" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "2.0 L WT Euro V",
      potencia: "145 Hp",
      torque: "190 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Manual LCST80 — 5 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.760 kg",
      capacidadCarga: "820 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Sensor de estacionamiento trasero", "Bloqueo de seguridad para niños"],
      tecnologia: ["Radio/MP3", "Bluetooth", "4 altavoces", "Control crucero"],
      equipamiento: ["Neumáticos 245/65R17", "Rines de aluminio", "Asientos de ecopiel", "Escalones laterales"],
    },
  },
  {
    name: "LA VENEZOLANA 4X2 DIESEL",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/02/jac_banners_la_venezolana_diesel_4x2_4x4.jpg",
    tagline: "Mayor eficiencia diésel para trabajo pesado",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.214,6",
    priceDirecta: "desde $3.214/mes",
    priceFacil: "desde $1.801/mes",
    colors: [
      { name: "Azul", hex: "#2563eb" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Blanco", hex: "#f5f5f5" },
    ],
    specs: {
      motor: "2.8 L WT Turbo Euro II",
      potencia: "137 Hp",
      torque: "210 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC5T80 — 5 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.815 kg",
      capacidadCarga: "900 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Sensor de estacionamiento trasero", "Bloqueo de seguridad para niños"],
      tecnologia: ["Radio/MP3", "Bluetooth", "4 altavoces"],
      equipamiento: ["Neumáticos 245/65R17", "Rines de aluminio", "Asientos de ecopiel", "Escalones laterales"],
    },
  },
  {
    name: "LA VENEZOLANA 4X4 DIESEL",
    tagline: "Potencia diésel y tracción total sin compromiso",
    transmission: "Manual",
    traction: "4x4",
    price: "$3.613,3",
    priceDirecta: "desde $3.613/mes",
    priceFacil: "desde $2.023/mes",
    colors: [
      { name: "Azul", hex: "#2563eb" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Blanco", hex: "#f5f5f5" },
    ],
    specs: {
      motor: "2.8 L WT Turbo Euro I",
      potencia: "137 Hp",
      torque: "210 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LC6T32 — 6 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Tambor (tras.) · ABS+EBD",
      dimensiones: "5.315 x 1.830 x 1.815 mm",
      pesoNeto: "1.930 kg",
      capacidadCarga: "900 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "Bloqueo de seguridad para niños", "Cerradura eléctrica"],
      equipamiento: ["Neumáticos 245/65R17", "Rines de aluminio", "Asientos de ecopiel", "Escalones laterales"],
    },
  },
  {
    name: "LA VENEZOLANA PRO 4X4",
    tagline: "La versión premium 2.0 Turbo + BELJIMMY 125",
    transmission: "Manual",
    traction: "4x4",
    price: "$4.165,2",
    priceDirecta: "desde $4.165/mes",
    priceFacil: "desde $2.295/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/06/jac_banners_la_venezolana_pro-1.jpg",
    specs: {
      motor: "2.0 L Turbo Euro V (enfriador interno)",
      potencia: "188 Hp",
      torque: "320 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Manual LC6T32 — 6 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Disco (tras.) · ABS+EBD",
      dimensiones: "5.325 x 1.880 x 1.830 mm",
      pesoNeto: "1.940 kg",
      capacidadCarga: "900 kg",
      tanque: "76 L",
      seguridad: ["2 airbags frontales", "ABS + EBD", "TPMS", "Arranque inteligente", "Bloqueo de seguridad para niños"],
      tecnologia: ["Sensor de estacionamiento trasero"],
      equipamiento: ["Neumáticos 265/60R18", "Rines de aluminio", "Luces LED DRL", "Escalones laterales", "Incluye BELJIMMY 125 (moto 125cc)"],
    },
  },
  {
    name: "DOBLE CABINA",
    tagline: "Pickup doble cabina diésel — 2 Ton de carga",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.713,3",
    priceFacil: "desde $2.255/mes",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Rojo", hex: "#dc2626" },
    ],
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LCST255M3 MT — 5 velocidades",
      suspension: ["Delantera: Ballestas delanteras 7", "Trasera: Ballestas traseras 4+6"],
      frenos: "Disco (del.) / Tambor (tras.)",
      dimensiones: "6.045 x 1.900 x 2.370 mm",
      pesoNeto: "2.560 kg",
      capacidadCarga: "2 Ton",
      tanque: "100 L",
      seguridad: ["Alarma de marcha atrás", "Cinturón regulable en altura", "Ventanas eléctricas"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16", "Rin de hierro"],
    },
  },
  {
    name: "C-3500 4X4",
    tagline: "Robusta y confiable · 3.5 Ton · Tracción 4x4",
    transmission: "Manual",
    traction: "4x4",
    price: "$4.709,3",
    priceFacil: "desde $2.637/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/01/C-3500-FERRETERO-4X4-1024x427.webp",
    colors: [
      { name: "Gris", hex: "#9ca3af" },
    ],
    specs: {
      motor: "2.8 L Diésel Euro II",
      potencia: "91 Hp",
      torque: "216 Nm",
      combustible: "Diésel",
      transmisionDetalle: "Manual LCST255M3 MT — 5 velocidades · Tracción 4x4",
      suspension: ["Delantera: Ballesta con amortiguador telescópico", "Trasera: Ballesta con amortiguador telescópico y auxiliar"],
      frenos: "Tambor hidráulico (del.) / Tambor hidráulico (tras.)",
      dimensiones: "5.445 x 1.952 x 2.300 mm",
      pesoNeto: "1.920 kg",
      capacidadCarga: "3.5 Ton",
      tanque: "85 L",
      seguridad: ["Dirección asistida", "Alarma de marcha atrás", "Freno de motor", "Cinturón ajustable"],
      tecnologia: ["Radio MP3"],
      equipamiento: ["Neumáticos 7.00R16 12PR", "Rin de hierro", "Ventana manual"],
    },
  },
  {
    name: "AVENTURA",
    tagline: "Pickup premium 231 HP · 4 modos de manejo",
    transmission: "Automática",
    traction: "4x4",
    price: "$5.259,0",
    colors: [
      { name: "Rojo", hex: "#dc2626" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "2.0 L Turbo Inyección Euro II",
      potencia: "231 Hp",
      torque: "380 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Automático AT A8R50 — 8 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "ABS + EBD",
      dimensiones: "5.330 x 1.965 x 1.920 mm",
      pesoNeto: "2.055 kg",
      capacidadCarga: "1.000 kg",
      tanque: "150 L",
      seguridad: ["2 airbags frontales", "TPMS", "Arranque inteligente", "Sensores delantero/trasero", "Cámara 360°", "Bloqueo de seguridad para niños"],
      tecnologia: ["Pantalla táctil 10,4\"", "Apple CarPlay / Android Auto", "Bluetooth", "Carga inalámbrica", "USB trasero", "6 altavoces"],
      equipamiento: ["Neumáticos 265/60R18", "Rines de aluminio", "Techo corredizo eléctrico", "Rieles de techo", "4 modos: Normal, Eco, Snow, Sport"],
    },
  },
  {
    name: "AVENTURA PRO",
    tagline: "Edición Limitada F-ROAD · Winche + Snorkel",
    transmission: "Automática",
    traction: "4x4",
    price: "$6.392,4",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/10/jac_banners_aventura_pro_edicion_limitada.jpg",
    colors: [
      { name: "Amarillo", hex: "#facc15" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
    specs: {
      motor: "2.0 L Turbo Inyección Euro II",
      potencia: "231 Hp",
      torque: "380 Nm",
      combustible: "Gasolina",
      transmisionDetalle: "Automático AT A8R50 — 8 velocidades",
      suspension: ["Delantera: Independiente de doble horquilla con resorte helicoidal", "Trasera: Eje rígido con ballestas no independientes"],
      frenos: "Disco (del.) / Disco (tras.) · ABS + EBD",
      dimensiones: "5.330 x 1.965 x 1.920 mm",
      pesoNeto: "2.055 kg",
      capacidadCarga: "1.000 kg",
      tanque: "150 L",
      seguridad: ["2 airbags frontales", "TPMS", "Arranque inteligente", "Sensores delantero/trasero", "Cámara 360°"],
      tecnologia: ["Pantalla táctil 10,4\"", "Apple CarPlay / Android Auto", "Bluetooth", "Carga inalámbrica", "6 altavoces"],
      equipamiento: ["Neumáticos 265/60R18", "Rines de aluminio", "Techo corredizo eléctrico", "Winche", "Snorkel", "Suspensión reforzada", "Mesetas reforzadas", "Rines reforzados"],
    },
  },
];

/* ══════════════════════════════════════════
   SUVs
   ══════════════════════════════════════════ */
export const suvModels: CarModel[] = [
  {
    name: "NEVADO MT",
    tagline: "El SUV familiar más completo del catálogo",
    transmission: "Manual",
    traction: "4x2",
    price: "$3.018,6",
    priceDirecta: "desde $3.018/mes",
    priceFacil: "desde $2.402/mes",
    featured: "MÁS CONSULTADO",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/vehiculo-nevado-js4-de-jac-motors-venezuela.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Gris", hex: "#9ca3af" },
    ],
  },
  {
    name: "ARENA SPORT MT",
    tagline: "SUV compacto, perfecto para la ciudad",
    transmission: "Manual",
    traction: "4x2",
    price: "$2.383,2",
    priceDirecta: "desde $2.564/mes",
    priceFacil: "desde $1.576/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/09/jac_banners_arena_sport_mt.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
    ],
  },
  {
    name: "ARENA SPORT AT",
    tagline: "Comodidad automática para el día a día",
    transmission: "Automática",
    traction: "4x2",
    price: "$2.586,2",
    priceDirecta: "desde $3.236/mes",
    priceFacil: "desde $1.694/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/09/jac_banners_arena_sport_at.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
    ],
  },
  {
    name: "NEVADO AT",
    tagline: "Turbo automático con techo corredizo eléctrico",
    transmission: "Automática",
    traction: "4x2",
    price: "$3.715,2",
    priceDirecta: "desde $3.715/mes",
    priceFacil: "desde $2.677/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/nevado-automatico-2025-de-jac-motors-venezuela.jpg",
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Azul", hex: "#2563eb" },
    ],
  },
  {
    name: "TEPUY PRO",
    tagline: "SUV premium · 181 HP Turbo DCT · Pantalla 24,6\"",
    transmission: "Automática",
    traction: "4x2",
    price: "$4.285,6",
    priceDirecta: "desde $5.259/mes",
    priceFacil: "desde $2.239/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/06/jac_banners_tepuy_pro.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
      { name: "Rojo", hex: "#dc2626" },
    ],
  },
  {
    name: "ARENA PRO XIP-4",
    tagline: "CVT automático con TPMS y faros LED",
    transmission: "Automática",
    traction: "4x2",
    price: "$2.824,7",
    priceDirecta: "desde $3.395/mes",
    priceFacil: "desde $2.083/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/jac_-motors_banners-Arena-Pro.png",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Plateado", hex: "#c0c0c0" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
    ],
  },
  {
    name: "LITE 5",
    tagline: "SUV espacioso · 182 HP Turbo DCT · Maletero 1.253 L",
    transmission: "Automática",
    traction: "4x2",
    priceDirecta: "desde $4.285/mes",
    priceFacil: "desde $2.924/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2024/09/js8-Savanna-jac-motors-venezuela.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Rojo", hex: "#dc2626" },
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Gris", hex: "#9ca3af" },
    ],
  },
  {
    name: "REFINE",
    tagline: "Van premium de pasajeros — confort y amplitud",
    transmission: "Automática",
    traction: "4x2",
    priceDirecta: "desde $4.728/mes",
    priceFacil: "desde $4.114/mes",
    image: "https://jacvenezuela.com/wp-content/uploads/2025/06/JAC-REFINE-EN-VENEZUELA.jpg",
    colors: [
      { name: "Blanco", hex: "#f5f5f5" },
      { name: "Negro", hex: "#1a1a1a" },
    ],
  },
];
